version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: "auto"
    groups:
      seam:
        patterns:
          - "@seamapi/*"
        update-types:
          - "minor"
          - "patch"
        dependency-type: "production"
    ignore:
      - dependency-name: "@seamapi/*"
        update-types: ["version-update:semver-major"]
