version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    versioning-strategy: "auto"
    allow:
      - dependency-name: "@seamapi/*"
      - dependency-type: production
    groups:
      seam:
        dependency-type: production
        update-types:
          - patch
          - minor
