name: Build and Release

on:
  push:
    branches:
      - issue-12-test # TODO remove
    tags:
      - "v*.*.*"
  # pull_request:
  #   branches:
  #     - issue-12-test # TODO remove

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}

      - name: Install pkg
        run: npm install -g pkg

      - name: Build the project
        run: npm run build

      - name: Build binaries with pkg
        run: npm run build:binaries

      - name: Get the version tag
        run: echo "VERSION_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Dry Run - Print the release version
        run: echo "Dry Run - Release version ${{ env.VERSION_TAG }}"

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: actions/create-release@v1
        with:
          tag_name: ${{ env.VERSION_TAG }}
          release_name: Release ${{ env.VERSION_TAG }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: Upload binaries to the release
      #   uses: actions/upload-release-asset@v1
      #   with:
      #     upload_url: ${{ steps.create_release.outputs.upload_url }}
      #     asset_path: ./path-to-binary/binaries
      #     asset_name: binary-name
      #     asset_content_type: application/octet-stream
      #   env:
